# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
# NOTE this is lower than the minimum version needed to run gradle, to help maximize compatibility
jdk = "11"
kotlin = "2.2.21"
android-compileSdk = "36"
android-minSdk = "21"
kotlinx-benchmark = "0.4.14"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.9.0" }

# Libraries can be bundled together for easier import
[bundles]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
android-library = { id = "com.android.library", version = "8.12.3" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "13.1.0" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinx-benchmark" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
